// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.32.1
// source: azd/extensions/v1beta/init.proto

package v1beta

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InitMessage struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	RequestId string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Error     *ExtensionError        `protobuf:"bytes,99,opt,name=error,proto3" json:"error,omitempty"`
	// Types that are valid to be assigned to MessageType:
	//
	//	*InitMessage_RegisterInitProviderRequest
	//	*InitMessage_RegisterInitProviderResponse
	//	*InitMessage_DetectRequest
	//	*InitMessage_DetectResponse
	MessageType   isInitMessage_MessageType `protobuf_oneof:"message_type"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitMessage) Reset() {
	*x = InitMessage{}
	mi := &file_azd_extensions_v1beta_init_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitMessage) ProtoMessage() {}

func (x *InitMessage) ProtoReflect() protoreflect.Message {
	mi := &file_azd_extensions_v1beta_init_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitMessage.ProtoReflect.Descriptor instead.
func (*InitMessage) Descriptor() ([]byte, []int) {
	return file_azd_extensions_v1beta_init_proto_rawDescGZIP(), []int{0}
}

func (x *InitMessage) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *InitMessage) GetError() *ExtensionError {
	if x != nil {
		return x.Error
	}
	return nil
}

func (x *InitMessage) GetMessageType() isInitMessage_MessageType {
	if x != nil {
		return x.MessageType
	}
	return nil
}

func (x *InitMessage) GetRegisterInitProviderRequest() *RegisterInitProviderRequest {
	if x != nil {
		if x, ok := x.MessageType.(*InitMessage_RegisterInitProviderRequest); ok {
			return x.RegisterInitProviderRequest
		}
	}
	return nil
}

func (x *InitMessage) GetRegisterInitProviderResponse() *RegisterInitProviderResponse {
	if x != nil {
		if x, ok := x.MessageType.(*InitMessage_RegisterInitProviderResponse); ok {
			return x.RegisterInitProviderResponse
		}
	}
	return nil
}

func (x *InitMessage) GetDetectRequest() *InitDetectRequest {
	if x != nil {
		if x, ok := x.MessageType.(*InitMessage_DetectRequest); ok {
			return x.DetectRequest
		}
	}
	return nil
}

func (x *InitMessage) GetDetectResponse() *InitDetectResponse {
	if x != nil {
		if x, ok := x.MessageType.(*InitMessage_DetectResponse); ok {
			return x.DetectResponse
		}
	}
	return nil
}

type isInitMessage_MessageType interface {
	isInitMessage_MessageType()
}

type InitMessage_RegisterInitProviderRequest struct {
	RegisterInitProviderRequest *RegisterInitProviderRequest `protobuf:"bytes,2,opt,name=register_init_provider_request,json=registerInitProviderRequest,proto3,oneof"`
}

type InitMessage_RegisterInitProviderResponse struct {
	RegisterInitProviderResponse *RegisterInitProviderResponse `protobuf:"bytes,3,opt,name=register_init_provider_response,json=registerInitProviderResponse,proto3,oneof"`
}

type InitMessage_DetectRequest struct {
	DetectRequest *InitDetectRequest `protobuf:"bytes,4,opt,name=detect_request,json=detectRequest,proto3,oneof"`
}

type InitMessage_DetectResponse struct {
	DetectResponse *InitDetectResponse `protobuf:"bytes,5,opt,name=detect_response,json=detectResponse,proto3,oneof"`
}

func (*InitMessage_RegisterInitProviderRequest) isInitMessage_MessageType() {}

func (*InitMessage_RegisterInitProviderResponse) isInitMessage_MessageType() {}

func (*InitMessage_DetectRequest) isInitMessage_MessageType() {}

func (*InitMessage_DetectResponse) isInitMessage_MessageType() {}

type RegisterInitProviderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterInitProviderRequest) Reset() {
	*x = RegisterInitProviderRequest{}
	mi := &file_azd_extensions_v1beta_init_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterInitProviderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterInitProviderRequest) ProtoMessage() {}

func (x *RegisterInitProviderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_azd_extensions_v1beta_init_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterInitProviderRequest.ProtoReflect.Descriptor instead.
func (*RegisterInitProviderRequest) Descriptor() ([]byte, []int) {
	return file_azd_extensions_v1beta_init_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterInitProviderRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type RegisterInitProviderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterInitProviderResponse) Reset() {
	*x = RegisterInitProviderResponse{}
	mi := &file_azd_extensions_v1beta_init_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterInitProviderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterInitProviderResponse) ProtoMessage() {}

func (x *RegisterInitProviderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_azd_extensions_v1beta_init_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterInitProviderResponse.ProtoReflect.Descriptor instead.
func (*RegisterInitProviderResponse) Descriptor() ([]byte, []int) {
	return file_azd_extensions_v1beta_init_proto_rawDescGZIP(), []int{2}
}

type InitDetectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectPath   string                 `protobuf:"bytes,1,opt,name=project_path,json=projectPath,proto3" json:"project_path,omitempty"`
	ProviderName  string                 `protobuf:"bytes,2,opt,name=provider_name,json=providerName,proto3" json:"provider_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitDetectRequest) Reset() {
	*x = InitDetectRequest{}
	mi := &file_azd_extensions_v1beta_init_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitDetectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitDetectRequest) ProtoMessage() {}

func (x *InitDetectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_azd_extensions_v1beta_init_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitDetectRequest.ProtoReflect.Descriptor instead.
func (*InitDetectRequest) Descriptor() ([]byte, []int) {
	return file_azd_extensions_v1beta_init_proto_rawDescGZIP(), []int{3}
}

func (x *InitDetectRequest) GetProjectPath() string {
	if x != nil {
		return x.ProjectPath
	}
	return ""
}

func (x *InitDetectRequest) GetProviderName() string {
	if x != nil {
		return x.ProviderName
	}
	return ""
}

type InitDetectResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Matched       bool                   `protobuf:"varint,1,opt,name=matched,proto3" json:"matched,omitempty"`
	Project       *InitProject           `protobuf:"bytes,2,opt,name=project,proto3" json:"project,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitDetectResponse) Reset() {
	*x = InitDetectResponse{}
	mi := &file_azd_extensions_v1beta_init_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitDetectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitDetectResponse) ProtoMessage() {}

func (x *InitDetectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_azd_extensions_v1beta_init_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitDetectResponse.ProtoReflect.Descriptor instead.
func (*InitDetectResponse) Descriptor() ([]byte, []int) {
	return file_azd_extensions_v1beta_init_proto_rawDescGZIP(), []int{4}
}

func (x *InitDetectResponse) GetMatched() bool {
	if x != nil {
		return x.Matched
	}
	return false
}

func (x *InitDetectResponse) GetProject() *InitProject {
	if x != nil {
		return x.Project
	}
	return nil
}

type InitProject struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Files         []*InitFile            `protobuf:"bytes,3,rep,name=files,proto3" json:"files,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitProject) Reset() {
	*x = InitProject{}
	mi := &file_azd_extensions_v1beta_init_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitProject) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitProject) ProtoMessage() {}

func (x *InitProject) ProtoReflect() protoreflect.Message {
	mi := &file_azd_extensions_v1beta_init_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitProject.ProtoReflect.Descriptor instead.
func (*InitProject) Descriptor() ([]byte, []int) {
	return file_azd_extensions_v1beta_init_proto_rawDescGZIP(), []int{5}
}

func (x *InitProject) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *InitProject) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *InitProject) GetFiles() []*InitFile {
	if x != nil {
		return x.Files
	}
	return nil
}

type InitFile struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Content       []byte                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitFile) Reset() {
	*x = InitFile{}
	mi := &file_azd_extensions_v1beta_init_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitFile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitFile) ProtoMessage() {}

func (x *InitFile) ProtoReflect() protoreflect.Message {
	mi := &file_azd_extensions_v1beta_init_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitFile.ProtoReflect.Descriptor instead.
func (*InitFile) Descriptor() ([]byte, []int) {
	return file_azd_extensions_v1beta_init_proto_rawDescGZIP(), []int{6}
}

func (x *InitFile) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *InitFile) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

var File_azd_extensions_v1beta_init_proto protoreflect.FileDescriptor

const file_azd_extensions_v1beta_init_proto_rawDesc = "" +
	"\n" +
	" azd/extensions/v1beta/init.proto\x12\x15azd.extensions.v1beta\x1a\"azd/extensions/v1beta/errors.proto\"\x9b\x04\n" +
	"\vInitMessage\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12;\n" +
	"\x05error\x18c \x01(\v2%.azd.extensions.v1beta.ExtensionErrorR\x05error\x12y\n" +
	"\x1eregister_init_provider_request\x18\x02 \x01(\v22.azd.extensions.v1beta.RegisterInitProviderRequestH\x00R\x1bregisterInitProviderRequest\x12|\n" +
	"\x1fregister_init_provider_response\x18\x03 \x01(\v23.azd.extensions.v1beta.RegisterInitProviderResponseH\x00R\x1cregisterInitProviderResponse\x12Q\n" +
	"\x0edetect_request\x18\x04 \x01(\v2(.azd.extensions.v1beta.InitDetectRequestH\x00R\rdetectRequest\x12T\n" +
	"\x0fdetect_response\x18\x05 \x01(\v2).azd.extensions.v1beta.InitDetectResponseH\x00R\x0edetectResponseB\x0e\n" +
	"\fmessage_type\"1\n" +
	"\x1bRegisterInitProviderRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"\x1e\n" +
	"\x1cRegisterInitProviderResponse\"[\n" +
	"\x11InitDetectRequest\x12!\n" +
	"\fproject_path\x18\x01 \x01(\tR\vprojectPath\x12#\n" +
	"\rprovider_name\x18\x02 \x01(\tR\fproviderName\"l\n" +
	"\x12InitDetectResponse\x12\x18\n" +
	"\amatched\x18\x01 \x01(\bR\amatched\x12<\n" +
	"\aproject\x18\x02 \x01(\v2\".azd.extensions.v1beta.InitProjectR\aproject\"z\n" +
	"\vInitProject\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x125\n" +
	"\x05files\x18\x03 \x03(\v2\x1f.azd.extensions.v1beta.InitFileR\x05files\"8\n" +
	"\bInitFile\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x18\n" +
	"\acontent\x18\x02 \x01(\fR\acontent2c\n" +
	"\vInitService\x12T\n" +
	"\x06Stream\x12\".azd.extensions.v1beta.InitMessage\x1a\".azd.extensions.v1beta.InitMessage(\x010\x01BGZEgithub.com/azure/azure-dev/cli/azd/pkg/azdext/contracts/v1beta;v1betab\x06proto3"

var (
	file_azd_extensions_v1beta_init_proto_rawDescOnce sync.Once
	file_azd_extensions_v1beta_init_proto_rawDescData []byte
)

func file_azd_extensions_v1beta_init_proto_rawDescGZIP() []byte {
	file_azd_extensions_v1beta_init_proto_rawDescOnce.Do(func() {
		file_azd_extensions_v1beta_init_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_azd_extensions_v1beta_init_proto_rawDesc), len(file_azd_extensions_v1beta_init_proto_rawDesc)))
	})
	return file_azd_extensions_v1beta_init_proto_rawDescData
}

var file_azd_extensions_v1beta_init_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_azd_extensions_v1beta_init_proto_goTypes = []any{
	(*InitMessage)(nil),                  // 0: azd.extensions.v1beta.InitMessage
	(*RegisterInitProviderRequest)(nil),  // 1: azd.extensions.v1beta.RegisterInitProviderRequest
	(*RegisterInitProviderResponse)(nil), // 2: azd.extensions.v1beta.RegisterInitProviderResponse
	(*InitDetectRequest)(nil),            // 3: azd.extensions.v1beta.InitDetectRequest
	(*InitDetectResponse)(nil),           // 4: azd.extensions.v1beta.InitDetectResponse
	(*InitProject)(nil),                  // 5: azd.extensions.v1beta.InitProject
	(*InitFile)(nil),                     // 6: azd.extensions.v1beta.InitFile
	(*ExtensionError)(nil),               // 7: azd.extensions.v1beta.ExtensionError
}
var file_azd_extensions_v1beta_init_proto_depIdxs = []int32{
	7, // 0: azd.extensions.v1beta.InitMessage.error:type_name -> azd.extensions.v1beta.ExtensionError
	1, // 1: azd.extensions.v1beta.InitMessage.register_init_provider_request:type_name -> azd.extensions.v1beta.RegisterInitProviderRequest
	2, // 2: azd.extensions.v1beta.InitMessage.register_init_provider_response:type_name -> azd.extensions.v1beta.RegisterInitProviderResponse
	3, // 3: azd.extensions.v1beta.InitMessage.detect_request:type_name -> azd.extensions.v1beta.InitDetectRequest
	4, // 4: azd.extensions.v1beta.InitMessage.detect_response:type_name -> azd.extensions.v1beta.InitDetectResponse
	5, // 5: azd.extensions.v1beta.InitDetectResponse.project:type_name -> azd.extensions.v1beta.InitProject
	6, // 6: azd.extensions.v1beta.InitProject.files:type_name -> azd.extensions.v1beta.InitFile
	0, // 7: azd.extensions.v1beta.InitService.Stream:input_type -> azd.extensions.v1beta.InitMessage
	0, // 8: azd.extensions.v1beta.InitService.Stream:output_type -> azd.extensions.v1beta.InitMessage
	8, // [8:9] is the sub-list for method output_type
	7, // [7:8] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_azd_extensions_v1beta_init_proto_init() }
func file_azd_extensions_v1beta_init_proto_init() {
	if File_azd_extensions_v1beta_init_proto != nil {
		return
	}
	file_azd_extensions_v1beta_errors_proto_init()
	file_azd_extensions_v1beta_init_proto_msgTypes[0].OneofWrappers = []any{
		(*InitMessage_RegisterInitProviderRequest)(nil),
		(*InitMessage_RegisterInitProviderResponse)(nil),
		(*InitMessage_DetectRequest)(nil),
		(*InitMessage_DetectResponse)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_azd_extensions_v1beta_init_proto_rawDesc), len(file_azd_extensions_v1beta_init_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_azd_extensions_v1beta_init_proto_goTypes,
		DependencyIndexes: file_azd_extensions_v1beta_init_proto_depIdxs,
		MessageInfos:      file_azd_extensions_v1beta_init_proto_msgTypes,
	}.Build()
	File_azd_extensions_v1beta_init_proto = out.File
	file_azd_extensions_v1beta_init_proto_goTypes = nil
	file_azd_extensions_v1beta_init_proto_depIdxs = nil
}
